# Generated by Django 5.1.2 on 2024-10-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegho.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='expAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegho.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='ExpProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('descricao', models.TextField()),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegho.dadospessoais')),
            ],
        ),
    ]
