# Generated by Django 5.1.2 on 2024-10-29 04:50

import django.core.validators
import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), main.validators.validate_email_registrado])),
                ('telefone', models.CharField(max_length=15, validators=[main.validators.validate_telefone])),
                ('endereco', models.CharField(max_length=100)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='main.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='ExpAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField(blank=True)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_academicas', to='main.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='ExpProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('termino', models.DateField(blank=True)),
                ('descricao', models.TextField()),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_profissionais', to='main.dadospessoais')),
            ],
        ),
    ]
